## global
seed: 31
device: cuda
mode: train
best_path: None
debug: False

## data
data_dir: data
bike_sharing_data: data/bike_sharing.csv   # Path to bike-sharing data
weather_data: data/weather.csv            # Path to weather data
taxi_trip_data: data/taxi_trips.csv       # Path to taxi trip records
poi_data: data/poi.csv                    # Path to Points of Interest (POI) data
road_network_data: data/road_network.csv  # Path to road networks data
graph_file: data/adj_mx.npz               # Adjacency matrix for graph-based methods
input_length: 19                          # Length of input sequence
batch_size: 32
test_batch_size: 32

## model
d_input: 2                 # Input features: e.g., inflow and outflow
d_output: 2                # Output predictions: e.g., inflow and outflow
d_model: 64
dropout: 0.2
percent: 0.1               # Data augmentation percentage
shm_temp: 0.5              # Temperature for spatial heterogeneity loss
nmb_prototype: 6           # Number of prototypes/clusters
yita: 0.6                  # Balance factor for inflow and outflow loss

## weather
weather_features:          # Features used from weather data
  - temperature
  - precipitation
  - wind_speed
  - humidity

## poi
poi_radius: 500            # Radius in meters for selecting POIs
poi_categories:            # Categories of POIs to consider
  - restaurant
  - entertainment
  - fitness
  - transportation
  - education

## road_network
road_connectivity: binary  # Connectivity type: binary or weighted
distance_metric: gaussian  # Metric to calculate distance between stations
max_distance: 1000         # Maximum distance in meters to consider connectivity

## train
epochs: 100
lr_init: 0.001
early_stop: True
early_stop_patience: 15
grad_norm: True
max_grad_norm: 5
use_dwa: True              # Whether to use dynamic weight averaging for loss balance
temp: 4                    # Temperature parameter for DWA
