dataset:
  name: MesowestWeather
  description: Weather data from the Mesowest API for spatio-temporal modeling
  paths:
    data: ./data/Mesowest/
    train: ./data/Mesowest/train.csv
    test: ./data/Mesowest/test.csv
  features:
    - timestamp
    - temperature
    - humidity
    - wind_speed
    - precipitation
    - visibility
  target:
    - temperature  # Can be used to predict temperature if necessary
  preprocessing:
    normalize: true
    fillna: "mean"
  temporal:
    time_steps: 6
    time_unit: "hour"
  split:
    train_ratio: 0.8
    test_ratio: 0.2
