dataset:
  name: NYCTaxi
  description: NYC yellow taxi trip dataset
  paths:
    data: ./data/NYCTaxi/
    train: ./data/NYCTaxi/train.csv
    test: ./data/NYCTaxi/test.csv
  features:
    - pickup_time
    - dropoff_time
    - pickup_location
    - dropoff_location
    - distance
    - fare_amount
    - passenger_count
    - trip_duration
  target:
    - trip_duration
  preprocessing:
    normalize: true
    fillna: "mean"
  temporal:
    time_steps: 8
    time_unit: "hour"
  split:
    train_ratio: 0.8
    test_ratio: 0.2
